name: Minimal WF test using Singularity

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "jonathan-branch-2" branch
  push:
    branches:
      - jonathan-branch-2

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test_WF
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        NXF_VER:
          - "21.10.6"
        # MUST use earlier version affected by this issue: https://github.com/nextflow-io/nextflow/issues/3023  - "latest-everything"
        RUN_PARAMS:
          - "-profile test48,singularity" 
          - "-profile test194,singularity"
          - "-profile test207,singularity"
          - "-profile test251,singularity"
    ## TODO: Set up tracking via tower for tests
    #environment: Nextflow_Tower
    #env:
    #   TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
    #   TOWER_WORKSPACE_ID: ${{ secrets.TOWER_WORKSPACE_ID }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1.1.0
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install Singularity
        run: |
          conda install -c conda-forge singularity -y
          export PATH=/usr/share/miniconda/bin:$PATH
          which singularity

      - name: Cache Singularity Images
        id: cache-singularity-images
        uses: actions/cache@v3
        with:
          path: |
            ./singularity
          key: Singularity_Image_Cache-${{ hashFiles('./singularity/*') }}

      - if: ${{ steps.cache-singularity-images.outputs.cache-hit == 'false' }}
        name: Pre-pull singularity
        run: |
          export PATH=/usr/share/miniconda/bin:$PATH
          bash "${GITHUB_WORKSPACE}/RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/NF_RCP-E_1.0.0/bin/prepull_singularity.sh" "${GITHUB_WORKSPACE}/RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/NF_RCP-E_1.0.0/config/software/by_docker_image.config"
          ls -l
          pwd

      - name: Run pipeline with test data
        run: |
          export NXF_SINGULARITY_CACHEDIR=$(pwd)/singularity
          export PATH=/usr/share/miniconda/bin:$PATH

          MAIN_NF="${GITHUB_WORKSPACE}/RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/NF_RCP-E_1.0.0/main.nf"
          nextflow run ${MAIN_NF}  ${{ matrix.RUN_PARAMS }} \
                  -name "GH_CI_$(date '+%s')" -ansi-log false  \
                  || { ORIG_ERROR=$?; cat .nextflow.log; exit ORIG_ERROR; } 
          nextflow run ${MAIN_NF}  ${{ matrix.RUN_PARAMS }} \
                  -name "GH_CI_$(date '+%s')" -entry POST_PROCESSING  -ansi-log false  \
                  || { ORIG_ERROR=$?; cat .nextflow.log; exit ORIG_ERROR; } 

      - name: Archive Workflow Logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: workflow-logs
          path: |
            ${{ github.workspace }}/GLDS-*/VV_Logs/*
            ${{ github.workspace }}/GLDS-*/Resource_Usage/*