name: Minimal WF test for nonGLDS

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "jonathan-branch-2" branch
  push:
    branches:
      - jonathan-branch-2

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Test_WF
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        NXF_VER:
          - "21.10.6"
        # MUST use earlier version affected by this issue: https://github.com/nextflow-io/nextflow/issues/3023  - "latest-everything"
        RUN_PARAMS:
          - "-profile test_nonGLDS,docker" 
    ## TODO: Set up tracking via tower for tests
    #environment: Nextflow_Tower
    #env:
    #   TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
    #   TOWER_WORKSPACE_ID: ${{ secrets.TOWER_WORKSPACE_ID }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1.1.0
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data
        run: |
          export PATH=/usr/share/miniconda/bin:$PATH
          MAIN_NF="${GITHUB_WORKSPACE}/RNAseq/Workflow_Documentation/NF_RCP-F/workflow_code/NF_RCP-E_1.0.0/main.nf"
          nextflow run ${MAIN_NF}  ${{ matrix.RUN_PARAMS }} \
                  -name "GH_CI_$(date '+%s')" -entry RCP  -ansi-log false  \
                  || { ORIG_ERROR=$?; cat .nextflow.log; exit ORIG_ERROR; }
          ls -l

      - name: Archive Workflow Logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: workflow-logs
          path: |
            ${{ github.workspace }}/CustomAnalysis/VV_Logs/*
            ${{ github.workspace }}/CustomAnalysis/Resource_Usage/*